"""analysis snapshot

Revision ID: eacd96d41524
Revises: 9fc63da2a5ab
Created: 2026-08-11 11:32:20.445168
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "eacd96d41524"
down_revision: str | None = "9fc63da2a5ab"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analysis_snapshot",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("period_id", sa.Uuid(), nullable=False),
        sa.Column("analysis_version", sa.String(length=16), nullable=False),
        sa.Column("metrics_version", sa.String(length=16), nullable=False),
        sa.Column("rules_version", sa.String(length=16), nullable=False),
        sa.Column("thresholds_version", sa.String(length=16), nullable=False),
        sa.Column("mappings_version", sa.String(length=16), nullable=False),
        sa.Column("evidence_version", sa.String(length=16), nullable=True),
        sa.Column("payload_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["period_id"], ["analysis_period.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "company_id", "period_id", "analysis_version", name="uq_snapshot_company_period_version"
        ),
    )
    op.create_index(
        "ix_snapshot_current",
        "analysis_snapshot",
        ["company_id", "period_id"],
        unique=True,
        postgresql_where=sa.text("is_current"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_snapshot_current",
        table_name="analysis_snapshot",
        postgresql_where=sa.text("is_current"),
    )
    op.drop_table("analysis_snapshot")
    # ### end Alembic commands ###
