"""company market, publication flag and fiscal calendar

Revision ID: 34e7eff2fc35
Revises: 654340e473e3
Created: 2026-08-12 07:27:27.983453
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "34e7eff2fc35"
down_revision: str | None = "654340e473e3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Server defaults are required, not cosmetic: the table already holds the
    # Israeli companies, and a NOT NULL column without one cannot be added to
    # a populated table.
    #
    # Both defaults are the conservative reading. Every existing row is an
    # Israeli issuer, so `il_ifrs` is a statement of fact rather than a guess.
    # `is_published` defaults to false so that nothing already loaded becomes
    # visible because a column appeared -- publication stays an explicit act.
    op.add_column(
        "company",
        sa.Column("market", sa.String(length=16), nullable=False, server_default="il_ifrs"),
    )
    op.add_column(
        "company",
        sa.Column("is_published", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        "company",
        sa.Column("fiscal_calendar_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("company", "fiscal_calendar_json")
    op.drop_column("company", "is_published")
    op.drop_column("company", "market")
    # ### end Alembic commands ###
