"""add patterns_version to analysis_snapshot

Revision ID: 654340e473e3
Revises: eacd96d41524
Created: 2026-08-11 18:35:30.211872
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "654340e473e3"
down_revision: str | None = "eacd96d41524"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "analysis_snapshot", sa.Column("patterns_version", sa.String(length=16), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("analysis_snapshot", "patterns_version")
    # ### end Alembic commands ###
