"""canonical financial schema

Revision ID: 9fc63da2a5ab
Revises: 3572107a2072
Created: 2026-08-09 16:03:48.292713
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "9fc63da2a5ab"
down_revision: str | None = "3572107a2072"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("provider_entity_id", sa.String(length=64), nullable=False),
        sa.Column("legal_name", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("name_en", sa.Text(), nullable=True),
        sa.Column("ticker", sa.String(length=32), nullable=True),
        sa.Column("security_number", sa.String(length=32), nullable=True),
        sa.Column("registry_id", sa.String(length=64), nullable=True),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("sector_code", sa.String(length=32), nullable=True),
        sa.Column("sector_name", sa.Text(), nullable=True),
        sa.Column("business_model", sa.String(length=64), nullable=True),
        sa.Column("company_stage", sa.String(length=32), nullable=True),
        sa.Column("reporting_currency", sa.String(length=3), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "provider_entity_id", name="uq_company_provider_entity"),
    )
    op.create_table(
        "metric_definition",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("display_name_he", sa.Text(), nullable=False),
        sa.Column("display_name_en", sa.Text(), nullable=False),
        sa.Column("description_he", sa.Text(), nullable=True),
        sa.Column("description_en", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("metric_type", sa.String(length=16), nullable=False),
        sa.Column("unit_type", sa.String(length=16), nullable=False),
        sa.Column("formula_version", sa.String(length=16), nullable=True),
        sa.Column("sector_scope", sa.String(length=32), nullable=False),
        sa.Column("is_core", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "analysis_period",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("fiscal_year", sa.Integer(), nullable=False),
        sa.Column("fiscal_quarter", sa.Integer(), nullable=False),
        sa.Column(
            "period_kind", sa.Enum("instant", "duration", name="period_kind"), nullable=False
        ),
        sa.Column(
            "duration_kind",
            sa.Enum("quarter", "ytd", "annual", "ttm", name="duration_kind"),
            nullable=True,
        ),
        sa.Column("period_start", sa.Date(), nullable=True),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(period_kind = 'instant' AND duration_kind IS NULL AND period_start IS NULL) OR (period_kind = 'duration' AND duration_kind IS NOT NULL AND period_start IS NOT NULL AND period_start <= period_end)",
            name="ck_period_kind_coherent",
        ),
        sa.CheckConstraint("fiscal_quarter BETWEEN 1 AND 4", name="ck_period_quarter_range"),
        sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_id", "code", name="uq_period_company_code"),
    )
    op.create_table(
        "concept_mapping",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("taxonomy", sa.String(length=32), nullable=True),
        sa.Column("raw_concept", sa.String(length=256), nullable=False),
        sa.Column("metric_code", sa.String(length=64), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("mapping_version", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("priority >= 0", name="ck_mapping_priority_non_negative"),
        sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["metric_code"], ["metric_definition.code"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider",
            "raw_concept",
            "company_id",
            "mapping_version",
            name="uq_mapping_concept_scope_version",
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_index(
        "ix_mapping_lookup",
        "concept_mapping",
        ["provider", "metric_code", "priority"],
        unique=False,
    )
    op.create_table(
        "filing",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("provider_filing_id", sa.String(length=64), nullable=False),
        sa.Column("report_type", sa.String(length=32), nullable=True),
        sa.Column("fiscal_year", sa.Integer(), nullable=True),
        sa.Column("fiscal_quarter", sa.Integer(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "recency_source",
            sa.Enum("provider", "inferred", "unknown", name="recency_source"),
            nullable=False,
        ),
        sa.Column("recency_key", sa.String(length=64), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("document_url", sa.Text(), nullable=True),
        sa.Column("source_format", sa.String(length=16), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("is_restatement", sa.Boolean(), nullable=False),
        sa.Column("supersedes_filing_id", sa.Uuid(), nullable=True),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["supersedes_filing_id"], ["filing.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "provider_filing_id", name="uq_filing_provider_id"),
    )
    op.create_index(
        "ix_filing_company_recency", "filing", ["company_id", "recency_key"], unique=False
    )
    op.create_table(
        "financial_fact",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("filing_id", sa.Uuid(), nullable=False),
        sa.Column("period_id", sa.Uuid(), nullable=False),
        sa.Column("origin", sa.Enum("reported", "derived", name="fact_origin"), nullable=False),
        sa.Column("raw_concept", sa.String(length=256), nullable=False),
        sa.Column("metric_code", sa.String(length=64), nullable=True),
        sa.Column("value", sa.Numeric(precision=38, scale=6), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("unit", sa.String(length=32), nullable=True),
        sa.Column("scale", sa.Integer(), nullable=True),
        sa.Column("decimals", sa.Integer(), nullable=True),
        sa.Column("statement", sa.Text(), nullable=True),
        sa.Column(
            "consolidation_scope",
            sa.Enum("consolidated", "separate", "unknown", name="consolidation_scope"),
            nullable=False,
        ),
        sa.Column("segment", sa.Text(), nullable=True),
        sa.Column("geography", sa.Text(), nullable=True),
        sa.Column("dimensions_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("dimensions_hash", sa.String(length=64), nullable=False),
        sa.Column("source_location", sa.Text(), nullable=True),
        sa.Column("source_text", sa.Text(), nullable=True),
        sa.Column(
            "quality_status",
            sa.Enum(
                "verified",
                "usable_with_warning",
                "incomplete",
                "not_comparable",
                "rejected",
                name="quality_status",
            ),
            nullable=False,
        ),
        sa.Column("derivation_formula", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["filing_id"], ["filing.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["metric_code"], ["metric_definition.code"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["period_id"], ["analysis_period.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "filing_id",
            "raw_concept",
            "period_id",
            "dimensions_hash",
            "origin",
            name="uq_fact_identity",
        ),
    )
    op.create_index(
        "ix_fact_company_concept_period",
        "financial_fact",
        ["company_id", "raw_concept", "period_id"],
        unique=False,
    )
    op.create_index(
        "ix_fact_company_metric_period",
        "financial_fact",
        ["company_id", "metric_code", "period_id"],
        unique=False,
    )
    op.create_table(
        "fact_derivation",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("derived_fact_id", sa.Uuid(), nullable=False),
        sa.Column("input_fact_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.CheckConstraint("derived_fact_id <> input_fact_id", name="ck_derivation_not_self"),
        sa.ForeignKeyConstraint(["derived_fact_id"], ["financial_fact.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["input_fact_id"], ["financial_fact.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("derived_fact_id", "ordinal", name="uq_derivation_ordinal"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("fact_derivation")
    op.drop_index("ix_fact_company_metric_period", table_name="financial_fact")
    op.drop_index("ix_fact_company_concept_period", table_name="financial_fact")
    op.drop_table("financial_fact")
    op.drop_index("ix_filing_company_recency", table_name="filing")
    op.drop_table("filing")
    op.drop_index("ix_mapping_lookup", table_name="concept_mapping")
    op.drop_table("concept_mapping")
    op.drop_table("analysis_period")
    op.drop_table("metric_definition")
    op.drop_table("company")
    # ### end Alembic commands ###

    # Autogenerate drops the tables but leaves the native enum types behind, so
    # a downgrade followed by an upgrade would fail with "type already exists".
    for enum_name in (
        "fact_origin",
        "quality_status",
        "consolidation_scope",
        "recency_source",
        "duration_kind",
        "period_kind",
    ):
        op.execute(sa.text(f"DROP TYPE IF EXISTS {enum_name}"))
